-- SQL skript pro vytvoření základních objektů schématu databáze.
-- Zadání č. 33. – Lékárna.
--------------------------------------------------------------------------------
-- Autor: Šerejch Radek <xserej00@stud.fit.vutbr.cz>.
-- Autor: Bakaj Štěpán <xbakaj00@stud.fit.vutbr.cz>.

-------------------------------- DROP ------------------------------------------


DROP TABLE Telefon;
DROP TABLE Zasoby_prodej;
DROP TABLE Prodej;
DROP TABLE Zasoby;
DROP TABLE Pojistovna;
DROP TABLE Zamestnanec;
DROP TABLE Lek;


-------------------------------- CREATE ----------------------------------------

CREATE TABLE Zamestnanec
(
    ID                    INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Jmeno                 VARCHAR(50),
    Prijmeni              VARCHAR(50),
    Mesto                 VARCHAR(50),
    PSC                   VARCHAR(6) CONSTRAINT PSC_check CHECK (REGEXP_LIKE(PSC, '^[0-9]{5}$')),
    Ulice                 VARCHAR(50),
    Cislo_popisne         INT,
    Cislo_bankovniho_uctu VARCHAR(40) CONSTRAINT ucet_check CHECK (REGEXP_LIKE(Cislo_bankovniho_uctu, '^(([0-9]{0,6})-)?([0-9]{2,10})\/([0-9]{4})$')),
    Predpisovy_prodej     NUMBER(1)
);



CREATE TABLE Prodej
(
    ID             INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Datum          TIMESTAMP(2),
    ID_zamestnance INT,
    CONSTRAINT zamestnanec_prodej_FK FOREIGN KEY (ID_zamestnance) REFERENCES Zamestnanec (ID) ON DELETE SET NULL
);

-- Zvolili jsme sloučení do jedné tabulky, protože se jednalo o přídání dvou atributů.

CREATE TABLE Lek
(
    Kod                INT PRIMARY KEY,
    Nazev              VARCHAR(50),
    Vyrobce            VARCHAR(50),
    Lekova_forma       VARCHAR(40),
    Cesta              VARCHAR(35),
    Ucina_latka        VARCHAR(100),
    Velikost_baleni    INT,
    Cena               INT,
    Prodej             VARCHAR(1) CHECK (Prodej IN ('V', 'R')),
    Doplatek           INT,
    Teplota_skladovani INT
);



CREATE TABLE Zasoby
(
    ID             INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Datum_spotreby DATE not null,
    Mnozstvi       INT,
    Kod_leku       INT,
    CONSTRAINT Lek_FK FOREIGN KEY (Kod_leku) REFERENCES Lek (Kod) ON DELETE SET NULL
);

CREATE TABLE Telefon
(
    ID_zamestnance INT,
    Poradove_cislo INT,
    Telefon        VARCHAR(25) NOT NULL CONSTRAINT telefon_check CHECK (REGEXP_LIKE(Telefon, '^(\+?420)?(2[0-9]{2}|3[0-9]{2}|4[0-9]{2}|5[0-9]{2}|72[0-9]|73[0-9]|77[0-9]|60[1-8]|56[0-9]|70[2-5]|79[0-9])[0-9]{3}[0-9]{3}$')),
    Popis          VARCHAR(255),
    PRIMARY KEY (ID_zamestnance, Poradove_cislo),
    CONSTRAINT Telefon_FK FOREIGN KEY (ID_zamestnance) REFERENCES Zamestnanec (ID) ON DELETE CASCADE
);

CREATE TABLE Pojistovna
(
    Kod   INT PRIMARY KEY,
    Nazev VARCHAR(255)
);

CREATE TABLE Zasoby_prodej
(
    ID_prodeje       INT,
    ID_zasoby        INT,
    Kod_pojistovny   INT,
    Cislo_pojistence VARCHAR(10) CONSTRAINT cislo_pojistence_check CHECK (REGEXP_LIKE(Cislo_pojistence, '^\d{2}(0[1-9]|1[0-2]|5[1-9]|6[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])\d{3,4}$'))
                                CONSTRAINT csl_poj_check CHECK(mod(Cislo_pojistence,11) = 0),
    PRIMARY KEY (ID_prodeje, ID_zasoby),
    CONSTRAINT Pojistovna_FK FOREIGN KEY (Kod_pojistovny) REFERENCES Pojistovna (Kod) ON DELETE SET NULL,
    CONSTRAINT Prodej_FK FOREIGN KEY (ID_prodeje) REFERENCES Prodej (ID) ON DELETE CASCADE ,
    CONSTRAINT Zasoby_FK FOREIGN KEY (ID_zasoby) REFERENCES Zasoby (ID) ON DELETE CASCADE
);


-------------------------------- INSERT VALUES ---------------------------------

INSERT INTO Zamestnanec ( Jmeno, Prijmeni, Mesto, PSC, Ulice, Cislo_popisne, Cislo_bankovniho_uctu,
                         Predpisovy_prodej)
VALUES ('Jan', 'Novák', 'Brno', 60200, 'Kolejní', 2, '123456789/9999', 1);
INSERT INTO Zamestnanec (Jmeno, Prijmeni, Mesto, PSC, Ulice, Cislo_popisne, Cislo_bankovniho_uctu, Predpisovy_prodej)
VALUES ('Jana', 'Nováková', 'Brno', 60200, 'Kolejní', 2, '987654321/9999', 0);
INSERT INTO Zamestnanec ( Jmeno, Prijmeni, Mesto, PSC, Ulice, Cislo_popisne, Cislo_bankovniho_uctu,
                         Predpisovy_prodej)
VALUES ( 'Josef', 'Kadlec', 'Kuřim', 66434, 'Stodolní', 28, '369258147/9999', 0);
INSERT INTO Zamestnanec ( Jmeno, Prijmeni, Mesto, PSC, Ulice, Cislo_popisne, Cislo_bankovniho_uctu,
                         Predpisovy_prodej)
VALUES ( 'Petra', 'Boháčková', 'Kuřim', 66434, 'Janáčkova', 50, '352477568/9999', 0);
INSERT INTO Zamestnanec ( Jmeno, Prijmeni, Mesto, PSC, Ulice, Cislo_popisne, Cislo_bankovniho_uctu,
                         Predpisovy_prodej)
VALUES ( 'Marek', 'Dočekal', 'Jihlava', 58601, 'Nerudova', 15, '31-548763892/8888', 1);

INSERT INTO Lek (Kod, Nazev, Vyrobce, Lekova_forma, Cesta, Ucina_latka, Velikost_baleni, Cena, Prodej, Doplatek,
                 Teplota_skladovani)
VALUES (0229792, 'IBALGIN', 'Sanofi', 'Potahovaná tableta', 'Perorální podání', 'IBUPROFEN', 36, 99, 'V', NULL, 25);
INSERT INTO Lek (Kod, Nazev, Vyrobce, Lekova_forma, Cesta, Ucina_latka, Velikost_baleni, Cena, Prodej, Doplatek,
                 Teplota_skladovani)
VALUES (0087906, 'KORYLAN', 'Zentiva', 'Tableta', 'Perorální podání', 'PARACETAMOL;HEMIHYDRÁT KODEIN-FOSFÁTU', 10, 120,
        'R', 50, 25);
INSERT INTO Lek (Kod, Nazev, Vyrobce, Lekova_forma, Cesta, Ucina_latka, Velikost_baleni, Cena, Prodej, Doplatek,
                 Teplota_skladovani)
VALUES (0254048, 'PARALEN', 'Zentiva', 'Tableta', 'Perorální podání', 'PARACETAMOL (PARACETAMOLUM)', 24, 59, 'V', NULL, 25);
INSERT INTO Lek (Kod, Nazev, Vyrobce, Lekova_forma, Cesta, Ucina_latka, Velikost_baleni, Cena, Prodej, Doplatek,
                 Teplota_skladovani)
VALUES (0223159, 'MUCOSOLVAN', 'Sanofi', 'Perorální roztok/roztok k inhalaci', 'Perorální/inhalační podání', 'AMBROXOL-HYDROCHLORID (AMBROXOLI HYDROCHLORIDUM)', 60, 108, 'V', NULL, 25);
INSERT INTO Lek (Kod, Nazev, Vyrobce, Lekova_forma, Cesta, Ucina_latka, Velikost_baleni, Cena, Prodej, Doplatek,
                 Teplota_skladovani)
VALUES (0059739, 'STREPSILS CITRON BEZ CUKRU', 'RECKITT BENCKISER', 'Pastilka', 'Orální podání', 'AMYLMETAKRESOL (AMYLMETACRESOLUM)2,4-DICHLORBENZYLALKOHOL (ALCOHOL 2,4-DICHLOROBENZYLICUS)', 24, 172, 'V', NULL, 25);

INSERT INTO Telefon(ID_zamestnance, Poradove_cislo, Telefon, Popis)
VALUES(1,1,'+420774023986','pracovni mobil');
INSERT INTO Telefon(ID_zamestnance, Poradove_cislo, Telefon, Popis)
VALUES(1,2,'+420774023123','osobni mobil');
INSERT INTO Telefon(ID_zamestnance, Poradove_cislo, Telefon, Popis)
VALUES(2,1,'+420774023321','osobni mobil');
INSERT INTO Telefon(ID_zamestnance, Poradove_cislo, Telefon, Popis)
VALUES(3,1,'+420605147852','osobni mobil');
INSERT INTO Telefon(ID_zamestnance, Poradove_cislo, Telefon, Popis)
VALUES(4,1,'+420731258764','osobni mobil');
INSERT INTO Telefon(ID_zamestnance, Poradove_cislo, Telefon, Popis)
VALUES(5,1,'+420702693216','osobni mobil');
INSERT INTO Telefon(ID_zamestnance, Poradove_cislo, Telefon, Popis)
VALUES(5,2,'+420731528416','pracovní mobil');

INSERT INTO Zasoby(Datum_spotreby,Mnozstvi,Kod_leku)
VALUES (TO_DATE('2023-01-01', 'yyyy/mm/dd'),10,0229792);
INSERT INTO Zasoby(Datum_spotreby,Mnozstvi,Kod_leku)
VALUES (TO_DATE('2023-01-01', 'yyyy/mm/dd'),5,0087906);
INSERT INTO Zasoby(Datum_spotreby,Mnozstvi,Kod_leku)
VALUES (TO_DATE('2024-01-01', 'yyyy/mm/dd'),10,0254048);
INSERT INTO Zasoby(Datum_spotreby,Mnozstvi,Kod_leku)
VALUES (TO_DATE('2024-01-01', 'yyyy/mm/dd'),5,0223159);
INSERT INTO Zasoby(Datum_spotreby,Mnozstvi,Kod_leku)
VALUES (TO_DATE('2024-01-01', 'yyyy/mm/dd'),5,0059739);

INSERT INTO Prodej(Datum,ID_zamestnance)
VALUES(TO_TIMESTAMP('2022-01-01 23:59:59.10', 'YYYY-MM-DD HH24:MI:SS.FF'),2);
INSERT INTO Prodej(Datum,ID_zamestnance)
VALUES(TO_TIMESTAMP('2022-01-02 00:05:59.10', 'YYYY-MM-DD HH24:MI:SS.FF'),1);
INSERT INTO Prodej(Datum,ID_zamestnance)
VALUES(TO_TIMESTAMP('2022-01-02 00:10:59.10', 'YYYY-MM-DD HH24:MI:SS.FF'),1);
INSERT INTO Prodej(Datum,ID_zamestnance)
VALUES(TO_TIMESTAMP('2022-01-03 08:22:59.10', 'YYYY-MM-DD HH24:MI:SS.FF'),4);
INSERT INTO Prodej(Datum,ID_zamestnance)
VALUES(TO_TIMESTAMP('2022-01-03 08:05:59.10', 'YYYY-MM-DD HH24:MI:SS.FF'),3);


INSERT INTO Pojistovna(Kod,Nazev)
VALUES (111,'všeobecná zdravotní pojišťovna');

INSERT INTO Zasoby_prodej(ID_prodeje,ID_zasoby)
VALUES(1,1);
INSERT INTO Zasoby_prodej(ID_prodeje,ID_zasoby)
VALUES(2,1);
INSERT INTO Zasoby_prodej(ID_prodeje,ID_zasoby,Kod_pojistovny,Cislo_pojistence)
VALUES(2,2,111,'0101019875');
INSERT INTO Zasoby_prodej(ID_prodeje,ID_zasoby)
VALUES(3,4);
INSERT INTO Zasoby_prodej(ID_prodeje,ID_zasoby)
VALUES(4,3);
INSERT INTO Zasoby_prodej(ID_prodeje,ID_zasoby)
VALUES(5,4);
INSERT INTO Zasoby_prodej(ID_prodeje,ID_zasoby)
VALUES(5,5);
INSERT INTO Zasoby_prodej(ID_prodeje,ID_zasoby)
VALUES(5,3);